"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.moveUp = exports.moveRight = exports.moveLeft = exports.moveDown = void 0;
var down_1 = require("./down");
Object.defineProperty(exports, "moveDown", { enumerable: true, get: function () { return down_1.moveDown; } });
var left_1 = require("./left");
Object.defineProperty(exports, "moveLeft", { enumerable: true, get: function () { return left_1.moveLeft; } });
var right_1 = require("./right");
Object.defineProperty(exports, "moveRight", { enumerable: true, get: function () { return right_1.moveRight; } });
var up_1 = require("./up");
Object.defineProperty(exports, "moveUp", { enumerable: true, get: function () { return up_1.moveUp; } });
